Acelerometro giroscopio sensores
Fic-Spinoff/family-care pull request #25
Opened 2018-04-10 22:26 UTC by faustinoco

Subi una primera versión para ver si sirve  así o quieres que cambie algo. Añadí también el sensor de contador de pasos porque con el acelerómetro y el giroscopio no encontré ninguna solución para la detección de caídas.

2018-04-11 21:53 UTC, zalito12 requested changes

2018-04-11 21:53 UTC, zalito12 commented on app/src/main/AndroidManifest.xml
> +<!--            <intent-filter>
No hace falta comentar esto. Se pueden tener varias actividades principales. Déjalo normal.

2018-04-11 21:53 UTC, zalito12 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".AccelerometerActivity">
Añade una propiedad ``label`` para que tengan otro nombre y se distingan. Por ejemplo ``android:label="Family Acelerometro"``, pero metelo en strings.

2018-04-11 21:53 UTC, zalito12 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".GyroscopeSensorActivity" />
A estas actividades ponles el ``intent-filter`` también.

2018-04-12 04:57 UTC, faustinoco commented
ya subi los cambios, cuando puedas revisarlo de nuevo, cualquier cosa me dices

2018-04-12 06:51 UTC, zalito12 approved these changes

2018-04-12 06:52 UTC, zalito12 commented
This PR resolves #22

2018-04-12 07:08 UTC, merged